# This nitebook is a refresher of Numpy functions in Linear Algebra and Matrices

In [1]:
import numpy as np
import time

In [ ]:
## Creation of vectors in Numpy

a = np.zeros(4)
print(f"")

In [6]:
b = np.zeros((4,8)) ## accepts shape as input argument
b

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
c = np.random.random_sample((4,2)) ## accepts shape as input arguments
c

array([[0.93613431, 0.98584005],
       [0.10121773, 0.52084557],
       [0.07788069, 0.45272159],
       [0.72586895, 0.55099632]])

In [23]:
## Some vector/data creation routines do not accept shape as input values
d = np.arange(0,10,2)
print(f"d :{d}")

e = np.random.rand(4)
print(f"e: {e}")

d :[0 2 4 6 8]
e: [0.63167768 0.69034065 0.41583276 0.13578824]


In [25]:
## Values in an array can also be specified manually
f = np.array([1.,2.,3.,7.]); print(f" data type: {f.dtype}, shape: {f.shape}")
g = np.array([1,2,3,7]); print(f"data type: {g.dtype}, shape: {g.shape}")

 data type: float64, shape: (4,)
data type: int64, shape: (4,)


### Operations On Vectors

1. Indexing: means referring to an element of an array by its position within the array
    
2. Slicing: means getting a subset of elements from an array based on their indices    

In [29]:
a = np.arange(10)
a[0], a[-1]

(0, 9)

Indexes must be within range of the vector

In [30]:
try: 
    c= a[10]
except Exception as e:
    print("Index out of bounds")
    print(e)

Index out of bounds
index 10 is out of bounds for axis 0 with size 10


In [32]:
a * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

### Vector Operations

Vector operations such as dot product, require the dimenions of the two vectors to  be the same.

In [37]:
def my_dot(a, b):
    x = 0
    for i in range(a.shape[0]):
        x = x + a[i] + b[i]
    return x    

In [38]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
my_dot(a,b)

24

The dot products returns a scalar

In [39]:
np.dot(a,b)

40